### ISSUE TITLE
YANG

### ISSUE THREAD

**Issue by sginoza** [rjsparks/id-guidelines#10]
Under formal languages, imho, it would be helpful to include some info about YANG, including that the module should be formatted using formatting option of PYANG or add a pointer to https://trac.ietf.org/trac/ops/wiki/yang-review-tools

One of our editors also suggests pointing to these documents:

RFC 8407 ("Guidelines for Authors and Reviewers of Documents Containing YANG Data Models")

RFC 8340 (tree diagrams)

perhaps refer to [YANG-SEC] again

**Comment by mskucherawy** [comment]
See also issue #2

**Comment by rjsparks** [comment]
fixed in 3229d444bc100ea5a8ff2c021a9ee21d66d9525a
