### ISSUE TITLE
Formal Languages section needs a subsection on YANG

### ISSUE THREAD

**Issue by rjsparks** [rjsparks/id-guidelines#2]
Per Sandy:

Imho, it would be helpful to include some info about YANG, including that the module should be formatted using formatting option of PYANG or add a pointer to https://trac.ietf.org/trac/ops/wiki/yang-review-tools

One of our editors also suggests pointing to these documents:

RFC 8407 ("Guidelines for Authors and Reviewers of Documents Containing YANG Data Models")

RFC 8340 (tree diagrams)

perhaps refer to [YANG-SEC] again

**Comment by mskucherawy** [comment]
Who might be a good person to contribute such a (hopefully brief but still useful) section about YANG?  It's definitely not my area.

**Comment by evyncke** [comment]
Rob Wilton is probably the best AD on this topic.
