### ISSUE TITLE
Refer to NISTIR 8366 for terminology

### ISSUE THREAD

**Issue by larseggert** [rjsparks/id-guidelines#4]
There will be an IESG statement shortly on recommending authors review [NISTIR 8366 ](https://doi.org/10.6028/NIST.IR.8366) for guidelines on using inclusive terminology. The community discussion on the terminology@ indicated support for also adding that recommendation to the author guidlines, i.e., this document. I believe John Levine has agreed with this. Hence, some text should be added to this document.

**Comment by mskucherawy** [comment]
I agree with this.

**Comment by rjsparks** [comment]
fixed in 3229d444bc100ea5a8ff2c021a9ee21d66d9525a
