### ISSUE TITLE
Normative reference when XML schema is used

### ISSUE THREAD

**Issue by rdanyliw** [rjsparks/id-guidelines#5]
As an analog to "If ABNF is used, ensure the I-D contains a normative reference to [RFC 5234]", it seems like any I-D that specifies an XML schema needs to refer to either:

https://www.w3.org/TR/xmlschema11-1/ or https://www.w3.org/TR/xmlschema11-2/.

**Comment by mskucherawy** [comment]
Sounds good to me.

**Comment by rjsparks** [comment]
fixed in 3229d444bc100ea5a8ff2c021a9ee21d66d9525a
