### ISSUE TITLE
Line limitations 

### ISSUE THREAD

**Issue by sginoza** [rjsparks/id-guidelines#7]
It seems like "and code" should be removed from the first bullet, since source code is covered in the next bullet.  Because the line limits are different, this may cause some confusion.

Verify that no text extends beyond the 72nd column of a line. This limit is especially important for diagrams and code, which the RFC Editor may not be able to trivially reformat to fall within the margins.

Verify that source code does not extend beyond the 69th column.

**Comment by mskucherawy** [comment]
Agree.

**Comment by rjsparks** [comment]
fixed in 3229d444bc100ea5a8ff2c021a9ee21d66d9525a
