### ISSUE TITLE
Ref format for I-Ds

### ISSUE THREAD

**Issue by sginoza** [rjsparks/id-guidelines#8]
I suggest referring to [RFCSTYLE] here, because the format shown in this doc does match what is in 7322.  The current format is shown in the web portion of the style guide <https://www.rfc-editor.org/styleguide/part2/>, and 7322bis recommends changing the format to add stream info.  

Verify that references to other Internet-Drafts are formatted as shown in [RFC7322]:
  Foo, "The Specific Subject", Work in Progress, 
  Internet-Draft, draft-foo-bar-specific-subject-00, 
  17 April 2021.

7322 shows:
      [RFCXXXX] Last name, First initial., Ed. (if applicable),
                "RFC Title", Sub-series number (if applicable),
                RFC number, Date of publication,
                <http://www.rfc-editor.org/info/rfc#>.

7322bis shows (Heather intended to add stream info):
   [RFCXXXX] Last name, First initial., Ed. (if applicable), "RFC
   Title", Stream, Sub-series number (if applicable), RFC number, RFC
   DOI, Date of publication, <https://www.rfc-editor.org/info/rfc#>
   (https://www.rfc-editor.org/info/rfc#).

**Comment by mskucherawy** [comment]
Agree.

**Comment by larseggert** [comment]
Any reason why I-Ds are not cited as "work in progress", as required by the boilerplate?

**Comment by sginoza** [comment]
Hi Lars,

“Work in Progress” needs to be added back per mail from Heather <https://www.rfc-editor.org/pipermail/rfc-interest/2019-September/010672.html> (thanks to Alice for finding this gem).  I just added this as an issue in GitHub for draft-flanagan-7322bis <https://github.com/rfc-format/draft-flanagan-7322bis>. 

Thanks,
Sandy
