### ISSUE TITLE
Nits

### ISSUE THREAD

**Issue by sginoza** [rjsparks/id-guidelines#9]
a) [RFC 7991] Appendix A1 --> s/A1/A.1

b) The majority of IETF stream documents I-Ds --> delete "documents"

c) update citation tags --> s/[RFC XXXX]/[RFCXXXX]

d) suggest reordering these - that way, all items are about IANA actions; last bullet about if there are no actions 

 - If there is no action for IANA, verify that this section explicitly says “This document has no IANA actions.” It is often helpful for the IANA Considerations section to remain in place upon publication as an RFC even if there are no actions.

 - If the document has considerable instructions for IANA actions, request an early review of the document by IANA.

e) is something intended in the quotes?

XML provides structures, such as the "" element information item in XML Schema, to allow element extensions.

**Comment by mskucherawy** [comment]
For (e) it should be "<any>" according to prior versions.

**Comment by rjsparks** [comment]
fixed in 3229d444bc100ea5a8ff2c021a9ee21d66d9525a
